###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class Agents(BaseModel):
    chatAgent: List["ChatAgent"]
    summary: Optional[str] = None

class Bus(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class Cell(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class ChatAgent(BaseModel):
    name: Optional[str] = None
    question: Optional[str] = None
    reason: Optional[str] = None
    dependent: Optional[str] = None

class DynamicOutput(BaseModel):
    model_config = ConfigDict(extra='allow')

class EventAll(BaseModel):
    eventKS: Optional["EventKS"] = None
    eventSB: Optional["EventSB"] = None
    eventTY: Optional["EventTY"] = None

class EventAndLocationTyRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    c: Optional[int] = None
    dc: Optional[int] = None
    r: Optional[str] = None

class EventFailAndLocationRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    c: Optional[int] = None
    r: Optional[str] = None

class EventKS(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    netEvent: List["types.NetEvent"]
    location: List["types.Location"]
    links: List["types.NetEventAndLocationRel"]

class EventSB(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    netEventFail: List["types.NetEventFail"]
    locationFail: List["types.LocationFail"]
    links: List["types.EventFailAndLocationRel"]

class EventTY(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    netEventTy: List["types.NetEventTy"]
    locationTy: List["types.LocationTy"]
    links: List["types.EventAndLocationTyRel"]

class IndexAndBusRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    v: Optional[str] = None
    j: Optional[str] = None
    z: Optional[str] = None
    m: Optional[str] = None

class IndexAndCellRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    v: Optional[str] = None
    j: Optional[str] = None
    z: Optional[str] = None
    m: Optional[str] = None

class IndexAndNetUnitRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    v: Optional[str] = None
    j: Optional[str] = None
    z: Optional[str] = None
    m: Optional[str] = None

class IndexAndTermRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    v: Optional[str] = None
    j: Optional[str] = None
    z: Optional[str] = None
    m: Optional[str] = None

class IndexCE(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    indexOfCell: List["types.IndexOfCell"]
    cell: List["types.Cell"]
    links: List["types.IndexAndCellRel"]

class IndexGL(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    indexOverview: List["types.IndexOverview"]
    netOverviewNodes: List["types.NetOverview"]
    links: List["types.IndexGlAndNetRel"]

class IndexGL4g(BaseModel):
    task_id: Optional[str] = None
    indexOverviewTriple4g: List["types.IndexOverviewTriple4g"]

class IndexGlAndNetRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    v: Optional[float] = None

class IndexGlAndNetRel4g(BaseModel):
    v: Optional[str] = None
    n: Optional[str] = None

class IndexNU(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    indexNetUnit: List["types.IndexNetUnit"]
    netUnit: List["types.NetUnit"]
    links: List["types.IndexAndNetUnitRel"]

class IndexNetUnit(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class IndexOfBus(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class IndexOfCell(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class IndexOfTerm(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class IndexOverview(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class IndexOverview4g(BaseModel):
    tp: Optional[str] = None
    n: Optional[str] = None

class IndexOverviewTriple4g(BaseModel):
    h: Optional["IndexOverview4g"] = None
    t: Optional["NetOverview4g"] = None
    r: Optional["IndexGlAndNetRel4g"] = None

class IndexYW(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    indexOfBus: List["types.IndexOfBus"]
    bus: List["types.Bus"]
    links: List["types.IndexAndBusRel"]

class IndexZD(BaseModel):
    extract_type: Optional[str] = None
    task_id: Optional[str] = None
    indexOfTerm: List["types.IndexOfTerm"]
    terminal: List["types.Terminal"]
    links: List["types.IndexAndTermRel"]

class Location(BaseModel):
    i: Optional[int] = None
    t: Optional[str] = None
    n: Optional[str] = None

class LocationFail(BaseModel):
    i: Optional[int] = None
    t: Optional[str] = None
    n: Optional[str] = None

class LocationTy(BaseModel):
    i: Optional[int] = None
    t: Optional[str] = None
    n: Optional[str] = None

class NetEvent(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class NetEventAndLocationRel(BaseModel):
    s: Optional[int] = None
    t: Optional[int] = None
    c: Optional[int] = None
    r: Optional[str] = None
    d: Optional[str] = None

class NetEventFail(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class NetEventTy(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class NetOverview(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class NetOverview4g(BaseModel):
    tp: Optional[str] = None
    n: Optional[str] = None

class NetUnit(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None

class PythonCode(BaseModel):
    code: Optional[str] = None

class Terminal(BaseModel):
    i: Optional[int] = None
    n: Optional[str] = None
