###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class Agents(BaseModel):
    chatAgent: List["ChatAgent"]
    summary: str

class Bus(BaseModel):
    i: int
    n: str

class Cell(BaseModel):
    i: int
    n: str

class ChatAgent(BaseModel):
    name: str
    question: str
    reason: str
    dependent: str

class DynamicOutput(BaseModel):
    model_config = ConfigDict(extra='allow')

class EventAll(BaseModel):
    eventKS: "EventKS"
    eventSB: "EventSB"
    eventTY: "EventTY"

class EventAndLocationTyRel(BaseModel):
    s: int
    t: int
    c: int
    dc: int
    r: str

class EventFailAndLocationRel(BaseModel):
    s: int
    t: int
    c: int
    r: str

class EventKS(BaseModel):
    extract_type: str
    task_id: str
    netEvent: List["NetEvent"]
    location: List["Location"]
    links: List["NetEventAndLocationRel"]

class EventSB(BaseModel):
    extract_type: str
    task_id: str
    netEventFail: List["NetEventFail"]
    locationFail: List["LocationFail"]
    links: List["EventFailAndLocationRel"]

class EventTY(BaseModel):
    extract_type: str
    task_id: str
    netEventTy: List["NetEventTy"]
    locationTy: List["LocationTy"]
    links: List["EventAndLocationTyRel"]

class IndexAndBusRel(BaseModel):
    s: int
    t: int
    v: str
    j: str
    z: str
    m: str

class IndexAndCellRel(BaseModel):
    s: int
    t: int
    v: str
    j: str
    z: str
    m: str

class IndexAndNetUnitRel(BaseModel):
    s: int
    t: int
    v: str
    j: str
    z: str
    m: str

class IndexAndTermRel(BaseModel):
    s: int
    t: int
    v: str
    j: str
    z: str
    m: str

class IndexCE(BaseModel):
    extract_type: str
    task_id: str
    indexOfCell: List["IndexOfCell"]
    cell: List["Cell"]
    links: List["IndexAndCellRel"]

class IndexGL(BaseModel):
    extract_type: str
    task_id: str
    indexOverview: List["IndexOverview"]
    netOverviewNodes: List["NetOverview"]
    links: List["IndexGlAndNetRel"]

class IndexGL4g(BaseModel):
    task_id: str
    indexOverviewTriple4g: List["IndexOverviewTriple4g"]

class IndexGlAndNetRel(BaseModel):
    s: int
    t: int
    v: float

class IndexGlAndNetRel4g(BaseModel):
    v: str
    n: str

class IndexNU(BaseModel):
    extract_type: str
    task_id: str
    indexNetUnit: List["IndexNetUnit"]
    netUnit: List["NetUnit"]
    links: List["IndexAndNetUnitRel"]

class IndexNetUnit(BaseModel):
    i: int
    n: str

class IndexOfBus(BaseModel):
    i: int
    n: str

class IndexOfCell(BaseModel):
    i: int
    n: str

class IndexOfTerm(BaseModel):
    i: int
    n: str

class IndexOverview(BaseModel):
    i: int
    n: str

class IndexOverview4g(BaseModel):
    tp: str
    n: str

class IndexOverviewTriple4g(BaseModel):
    h: "IndexOverview4g"
    t: "NetOverview4g"
    r: "IndexGlAndNetRel4g"

class IndexYW(BaseModel):
    extract_type: str
    task_id: str
    indexOfBus: List["IndexOfBus"]
    bus: List["Bus"]
    links: List["IndexAndBusRel"]

class IndexZD(BaseModel):
    extract_type: str
    task_id: str
    indexOfTerm: List["IndexOfTerm"]
    terminal: List["Terminal"]
    links: List["IndexAndTermRel"]

class Location(BaseModel):
    i: int
    t: str
    n: str

class LocationFail(BaseModel):
    i: int
    t: str
    n: str

class LocationTy(BaseModel):
    i: int
    t: str
    n: str

class NetEvent(BaseModel):
    i: int
    n: str

class NetEventAndLocationRel(BaseModel):
    s: int
    t: int
    c: int
    r: str
    d: str

class NetEventFail(BaseModel):
    i: int
    n: str

class NetEventTy(BaseModel):
    i: int
    n: str

class NetOverview(BaseModel):
    i: int
    n: str

class NetOverview4g(BaseModel):
    tp: str
    n: str

class NetUnit(BaseModel):
    i: int
    n: str

class PythonCode(BaseModel):
    code: str

class Terminal(BaseModel):
    i: int
    n: str
