spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:semantic;DATABASE_TO_UPPER=false;QUERY_TIMEOUT=30
    username: root
    password: semantic
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql,classpath:db/schema-h2-demo.sql
      data-locations: classpath:db/data-h2.sql,classpath:db/data-h2-demo.sql
  h2:
    console:
      path: /h2-console/semantic
      enabled: true