# 检查系统句柄数
worker_rlimit_nofile 65530;
# 检查Nginx运行用户是否合理
user nobody nogroup;
worker_processes 1;
worker_cpu_affinity auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 65530; # 检查是否设置单个进程最大连接数
}

http {
    error_log /var/log/nginx/error.log warn; # 检查是否配置错误日志文件
    access_log /var/log/nginx/access.log; # 检查是否配置访问日志文件
    limit_conn_zone $binary_remote_addr zone=addr:10m; # 限制同一客户端ip地址
    limit_conn_zone $server_name zone=perserver:10m; # 限制同一server地址
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 基本超时设置
    keepalive_timeout 600s; # 检查是否设置控制超时时间
    client_header_timeout 600s;
    client_body_timeout 600s;
    send_timeout 600s; # 超时时间

    # 代理设置
    proxy_connect_timeout 600s;
    proxy_read_timeout 600s;  # 长轮询或大文件下载可能需要更长时间
    proxy_send_timeout 600s;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile on;
    server {
        listen 9000;
        server_name localhost;

        client_max_body_size 200M; # 上传文件大小限制
        client_body_buffer_size 16k;
        client_header_buffer_size 1k;
        large_client_header_buffers 4 8k;
        client_header_timeout 300s;
        client_body_timeout 300s;
        keepalive_timeout 300; # 长连接持续时间
        send_timeout 300s; # 超时时间
        sendfile on; # 上传加速

        add_header X-Frame-Options SAMEORIGIN; # 检查是否限制跨域访问
        gzip on; # 是否开启gzip
        gzip_buffers 32 4K; # 缓冲(压缩在内存中缓冲几块? 每块多大?)
        gzip_comp_level 6; # 推荐6 压缩级别(级别越高,压的越小,越浪费CPU计算资源)
        gzip_min_length 1k; # 开始压缩的最小长度(再小就不要压缩了,意义不在)
        gzip_types application/javascript text/css text/xml application/octet-stream; # 对哪些类型的文件用压缩 如txt,xml,html ,css
        gzip_disable "MSIE [1-6]\."; #正则匹配UA，配置禁用gzip条件。此处表示ie6及以下不启用gzip（因为ie低版本不支持）
        gzip_http_version 1.1; # 开始压缩的http协议版本(可以不设置,目前几乎全是1.1协议)
        gzip_vary on; # 是否传输gzip压缩标志

        server_tokens off; # 检查是否隐藏Nginx版本号
        limit_conn addr 1000; # 检查是否限制客户端下载的并发连接数
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;# 检查是否禁用强度较弱的加密套件 配置ssl加密算法
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # 检查是否配置支持的ssl协议限制
        ssl_prefer_server_ciphers on; # 检查是否使用安全加密套件

        absolute_redirect off;  # 关闭绝对重定向
        port_in_redirect off;   # 禁止重定向携带端口

        # 静态资源（优先匹配）
        location ~ ^/(static|favicon.ico|robots.txt) {
            root /usr/share/nginx/html/supersonic-webapp;
            expires 30d;
            access_log off;
            add_header Cache-Control "public, immutable";
        }

        # 前端动态路由
        location /webapp {
            alias /usr/share/nginx/html/supersonic-webapp;
            try_files $uri $uri/ /supersonic-webapp/index.html;
        }

        # 根目录重定向
        location / {
            root /usr/share/nginx/html/supersonic-webapp;
            index  index.html;
            try_files $uri $uri/ /index.html;
            add_header X-Frame-Options ALLOWALL;
            proxy_hide_header X-Frame-Options;
        }

       location /api/ {
            proxy_pass http://192.168.16.10:32513/api/; # 集成部署
#             proxy_pass http://192.168.16.10:31160/api/; # 单独部署
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            limit_rate 2048k;
            # 与后端服务器建立连接的超时时间，默认为60秒
            proxy_connect_timeout 600s;
            # 向后端服务器发送请求的超时时间，默认为60秒
            proxy_send_timeout 600s;
            # 从后端服务器读取响应的超时时间，默认为60秒
            proxy_read_timeout 600s;
        }

    }

}