coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=18080
discovery.uri=http://localhost:18080
# http-server.authentication.type=PASSWORD
# internal-communication.shared-secret=sharedsecret
# When set to dynamic, catalog configuration can also be managed using CREATE CATALOG and DROP CATALOG
catalog.management=dynamic
# When set to file, creating and dropping catalogs using the SQL commands adds and removes catalog property files on the coordinator node. Trino server process requires write access in the catalog configuration directory. Existing catalog files are also read on the coordinator startup
# catalog.store=file
# catalog.config-dir=etc/catalog/

# ????????????????????????
query.max-execution-time=2h
# ??????????????????????
query.max-run-time=1h
# ????? CPU ????? Worker ? CPU ?????
query.max-cpu-time=8h